author: "Tobe O <thosakwe@gmail.com>"
description: "Dart port of Esprima 3.1."
homepage: "https://github.com/thosakwe/dart_esprima.git"
name: "esprima"
version: "3.1.2-dev"
dev_dependencies: 
  test: "^0.12.16"
